---
title: "PESCAR tutorial simulation"
author: "Fred White"
vignette: >
  %\VignetteIndexEntry{PESCAR tutorial simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document: default
  header-includes:
  - \usepackage{multicol}
  - \usepackage{amsmath}
  - \usepackage{float}
  - \usepackage{bm}
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(PESCAR)
```

```{r, message=FALSE}
#load libraries
library(scales)
library(ggpubr)
library(extrafont)
library(GGally)
# library(tidyverse)
library(Matrix)
library(MASS)
library(pracma)    # - WARNING - conflicting ones() function with RpESCA
library(RpESCA)
library(tidygraph)
library(ggraph)
library(igraph)



```


We begin by simulating high-dimensional datasets and the corresponding response.

```{r simulate-data}


getwd()
#
# Yweights <- c(0.5, 0.05, 0.3)  #0.5




Yweights <- c(0, 0, 0.5, 0.5)  #0.5     #      0,0,-0.01,0.01




                      
K <- 6

# System graph across all components 
# g <- generate_component_graph(num_components = K, edge_prob = 0.4, seed = 5)     # warning - need to add logic for block specific edge overlap  

block_names <- c("chems", "genes", "bact")

# For each component r = 1..6, which blocks it belongs to:
blocks_list <- list(      #V(g)$blocks
  c("chems","genes","bact"),   # comp 1: C
  c("chems","genes","bact"),   # comp 2: C
  c("chems","bact"),           # comp 3: L (chems + bact)
  c("genes","bact"),           # comp 4: L (genes + bact)
  c("genes"),                  # comp 5: D (genes-only)
  c("chems")                   # comp 6: D (chems-only)
)


generate_component_graph_constrained <- function(blocks_list,
                                                 edge_prob = 0.4,
                                                 seed = NULL,
                                                 directed = FALSE) {
  if (!is.null(seed)) set.seed(seed)

  K <- length(blocks_list)
  stopifnot(K >= 1)

  # helper: do two nodes share at least 1 block?
  shares_block <- function(i, j) length(intersect(blocks_list[[i]], blocks_list[[j]])) > 0L

  # all possible pairs (upper triangle)
  pairs <- combn(K, 2)
  keep  <- apply(pairs, 2, function(idx) shares_block(idx[1], idx[2]))

  allowed_pairs <- pairs[, keep, drop = FALSE]

  g <- make_empty_graph(n = K, directed = directed)
  V(g)$name   <- as.character(seq_len(K))
  V(g)$blocks <- blocks_list

  # sample edges only from allowed pairs
  if (ncol(allowed_pairs) > 0) {
    take <- runif(ncol(allowed_pairs)) < edge_prob
    chosen <- allowed_pairs[, take, drop = FALSE]

    if (ncol(chosen) > 0) {
      g <- add_edges(g, as.vector(chosen))
    }
  }

  g
}

g <- generate_component_graph_constrained(
  blocks_list = blocks_list,
  edge_prob   = 0.4,
  seed        = 104
)


get_CLD_type <- function(blocks_vec, all_blocks) {
  k <- length(blocks_vec)
  if (k == length(all_blocks)) return("C")
  if (k == 1L)                 return("D")
  if (k > 1L)                  return("L")
  return("None")  
}

V(g)$type <- vapply(
  V(g)$blocks,
  get_CLD_type,
  character(1),
  all_blocks = block_names
)

E(g)$pattern <- sample(c("circle","opposite","corr_pos","corr_neg","spiral","same"),size = length(E(g)), replace = TRUE)

cg1 <- g

cg1_tbl <- as_tbl_graph(cg1) %>%
  mutate(
    # turn list-column "blocks" into a single label per node
    block_group = sapply(blocks, paste, collapse = "+"),
    type        = factor(type)
  ) %>%
  activate(edges) %>%
  mutate(pattern = factor(pattern))

ggraph(cg1_tbl, layout = "fr") +
  geom_edge_link(aes(colour = pattern), alpha = 0.7) +
  geom_node_point(aes(fill = block_group), size = 6, shape = 21, colour = "black") +
  geom_node_text(aes(label = name), repel = TRUE) +
  scale_edge_colour_discrete(name = "Edge pattern") +
  scale_fill_discrete(name = "Blocks") +
  theme_graph()

# #SIMULATION2
                       simulation = PESCAR:::dataSimWrapper(Yweights = Yweights,   #0
                              componentWeights = list(c(0.5,0.5,0.5,0.5, 0.5),
                                                      c(0.5,0.5,0.5,0.5),
                                                      c(0.5,0.5,0.5, 0.5)),
                              Ynoise_sd = 0.01, error_weights = c(0.2,0.2,0.2),    #0.5 # 2     POLYS - 2,2,2
                              numFeatures_chems = (c(10,5,10,5,10,5,10)), #redundant with topology
                              numFeatures_bact = (c(0,0,10,5,10,0,0)),     #redundant with topology
                              numFeatures_genes = (c(10,5,10,5,10,0,0)),    #redundant with topology
                              seed = 123,
                              polydemo = T,
                             component_graph = g,      # topology
                          topology_pure_frac = 0.3)
      
            
                        
                        
      


if(length(Yweights < 6)){
  Yweights <- c(Yweights, rep(0, 6-length(Yweights)))
}





#can predict y at iteration 0, X blocks need to be more complex?
# - TODO - add components of structured noise on top

Data = simulation[[1]]
y = simulation[[3]]
Data[[length(Data)+1]] <- y # add y as the fourth block

colnames(Data[[4]]) <- paste0("Y_", 1:ncol(y))


names(Data) <- c("Metabolite","Gene","Bacteria","Y")

names(Data) <- c("X1","X2","X3","Y")


# Data <- lapply(Data,F_scale)

```



```{r}
# debug_path <- file.path(Sys.getenv("USERPROFILE"), "Documents", "PESCAR_vignette_debug.rds")
# 
# finite_n <- function(x) sum(is.finite(suppressWarnings(as.numeric(x))))
# finite_sd <- function(x) {
#   x <- suppressWarnings(as.numeric(x))
#   stats::sd(x[is.finite(x)], na.rm = TRUE)
# }
# 
# suspects <- c("dataSimWrapper")  # add more function names here if needed
# 
# fun_fingerprints <- lapply(suspects, function(nm) {
#   f <- get(nm, envir = asNamespace("PESCAR"), inherits = FALSE)
#   list(
#     name = nm,
#     body = paste(deparse(body(f)), collapse = "\n")
#   )
# })
# names(fun_fingerprints) <- suspects
# 
# dbg <- list(
#   wd = getwd(),
#   search = search(),
#   loaded = loadedNamespaces(),
#   session = utils::sessionInfo(),
#   object_names = ls(),
#   fun_fingerprints = fun_fingerprints
# )
# 
# # add your actual object here, e.g. dat_plot / df / whatever goes into ggpairs
# if (exists("dat_plot")) {
#   dbg$finite_counts <- vapply(dat_plot, finite_n, integer(1))
#   dbg$finite_sd <- vapply(dat_plot, finite_sd, numeric(1))
#   dbg$na_counts <- vapply(dat_plot, function(x) sum(is.na(x)), integer(1))
# }
# 
# saveRDS(dbg, debug_path)
# stop(paste("Debug checkpoint written to", debug_path))


```

```{r}
# browser()
```



```{r, message=FALSE, warnings=FALSE}
library(ggplotify)
library(patchwork)
pdf <- cbind.data.frame("ID" = rep(names(Data), lapply(Data,ncol)), rbind(simulation[[2]], Yweights))
# B_sim_pairs <-GGally::ggpairs(pdf, columns = 2:ncol(pdf), mapping = aes(colour = ID))
# B_sim_pairs

B_sim_pairs <- GGally::ggpairs(
  pdf,
  columns = 2:ncol(pdf),
  upper = list(continuous = "blank"),
  mapping = ggplot2::aes(colour = ID)
)
B_sim_pairs
```




```{r option settings}
 dataTypes <- "GGG"
  
  # concave function and its hyper-parameter
  fun_concave <- 'gdp'; gamma <- 1;
  penalty = 'L2' # concave L2 norm penalty
  
  #no alpha estimation for y as cannot perform svd on 1 variable (?)
  alpha_result = PESCAR:::pesca_estimate_alphas(datasets=Data[1:3], numComponents=2:15, CVfolds=3)   
  alpha_est = alpha_result[[1]]
  roels_alphas_stds = alpha_result[[2]]
  R_selected_list = alpha_result[[3]]
  cvErrors_list = alpha_result[[4]]
  
  
  opts <- PESCAR:::generate_options(gamma = gamma, alpha_est = alpha_est)
  opts$maxit <- 10000
  
  
  opts$tol_obj <- 1e-8

  dataTypes <- "GGGG"
    opts$alphas[4] <- mean(opts$alphas)


  nTries <- 3

 # Data[[4]] <- F_scale(y)

```

*SIDE NOTE* Here we split the data in order to check back later whether the model works.

```{r}
#randomly sample data to leave a few distributed samples for investigating y prediction

set.seed(129)
inds <- sample(nrow(Data[[1]]), 60)
inds <- inds[order(inds)]

i <- NULL
newdata <- list()
for(i in 1:3){
  newdata[[i]] <- Data[[i]][inds,]
  
}

y_samp <- Data[[4]][inds,]





spikes_from_sim <- function(simulation){
  #get spikes from sim
  
  yWeights <- simulation[[4]]      # - WARNING -
  loadings <- simulation[[2]]
  
  yWeights <- c(yWeights,rep(0,ncol(loadings) - length(yWeights)))
  
  
  cands <- loadings %*% yWeights
  
  
  cands <- cands[order(abs(cands[,1]), decreasing = T),]
  
  spikes <- cands[which(cands != 0)]
  return(spikes)
}

```

```{r}
opts$R <- 6




opts$rand_start <- "PLS"  #"rand_orth" # "FIXED" #"rand_orth"  #1 #0  #    
newdata <- Data[1:3]
y_samp <- Data[[4]]

  dataTypes = rep("G",3 )
 opts <- PESCAR:::reset_A0_B0(opts)
  alpha <- 0.75  # 0.5      #0.9999 mainly fit X - still easy to predict y...
   nTriesy <- 10

     lambdas_CVy <-  log10_seq(from=0.001, to=2, length.out=nTriesy)   # c(0.15,0.2)#,0.5,0.55)
     lambdas_CV <- log10_seq(from=0.001, to=10, length.out=5)       #c(1,1.5,2)#,2.5)

            if(alpha == 1){lambdas_CVy <- 0.1; opts$rand_start <- 0}   # doesnt matter which value as it has no effect at this alpha level - to prevent pointless CV runs

     
     # WARM START - > OFF in 
       opts$save_history <- FALSE

     
     model <- list (simulation[[5]],simulation[[2]],RpESCA::ones(nrow(simulation[[2]])))
     

  result_CV <- PESCAR:::pESCA_CV_DEV(dataSets = newdata, 
                            dataTypes = dataTypes,
                            y = y_samp,
                            lambdas_CV = lambdas_CV,
                            lambdas_CVy = lambdas_CVy,
                            penalty=penalty,
                            fun_concave=fun_concave,
                            alpha = alpha,
                            opts=opts,
                            ORTH_A = TRUE,
                            rstartseed = 31)   # FALSE fails      #"simulation[[5]]"   #1
  
```



Beta = A_old’*y, so yhat*Beta’ = yhat*y’*A_old.

A_new = pi* Xhat*Bhat + (1-pi)*yhat * y’ * A_old 


Beta = A_old’*y only when AtA = I which is not true at k = 1




```{r}
# - WARNING - 
index_min_cv <- which.min(result_CV$cvErrors_mat[,1])      # - WARNING - !!



d <- result_CV$cvErrors_mat
d <- cbind(d,c(1:nrow(d)))
D <- d[order(d[,1],d[,5],decreasing=FALSE),]
front <- D[which(!duplicated(cummin(D[,5]))),,drop = FALSE]


index_min_cv <- which.min(result_CV$cvErrors_mat[,1])

if(nrow(front) > 1){
  


mat <- front[,c(1,5)]


minv <- apply(mat, 2, min)
rng  <- apply(mat, 2, function(z) diff(range(z)))
Z    <- sweep(sweep(mat, 2, minv, "-"), 2, rng, "/")   # min–max to [0,1]

d2   <- sqrt(rowSums(Z^2))          # Euclidean to (0,0)
dInf <- apply(Z, 1, max)            # Chebyshev to (0,0)

best_L2   <- which.min(d2)
best_LInf <- which.min(dInf)

best_L2; best_LInf
mat[best_L2, ]; mat[best_LInf, ]



index_min_cv <- front[best_L2,6]

}






# index_min_cv <- which.min(result_CV_df$GMR)

# index_min_cv <- 33

lambda_vals <- rep(lambdas_CV, each = length(lambdas_CVy))  # x-axis
lambda_y_vals <- rep(lambdas_CVy, times = length(lambdas_CV))

lambdas <- rep(lambda_vals[index_min_cv], length(Data))
lambdas_y <- lambda_y_vals[index_min_cv]



# index_min_cv <- 23#23   #5

PESCARmod <- result_CV$TrainModel[[index_min_cv]]

```

```{r}
plot(result_CV$cvErrors_mat[,1],result_CV$cvErrors_mat[,5])
lines(front[,1],front[,5])


```


```{r}
#over and under metrics - meeting Age


#UNDER

#Is est in true?

A <- PESCARmod$outcome$A
#1
E1u <- A - (simulation[[5]] %*% solve(t(simulation[[5]]) %*% simulation[[5]]) %*% t(simulation[[5]]) %*% A)

E1u <- A - (simulation[[5]] %*% t(simulation[[5]]) %*% A)

norm(E1u, type = "F")


#2

#Is Y_rel in est?

Xy <- simulation[[5]][,Yweights != 0, drop = FALSE]

E2u <- Xy - (A %*% solve(t(A) %*% A) %*% t(A) %*% Xy)

E2u <- Xy - (A %*% t(A) %*% Xy)

norm(E2u, type = "F")



#OVER

#3

#Is true in est?

E3u <- simulation[[5]] - (A %*% solve(t(A) %*% A) %*% t(A) %*% simulation[[5]])

E3u <- simulation[[5]] - (A %*% t(A) %*% simulation[[5]])

norm(E3u, type = "F")



#4

#Is est in true? (same as 1)






```



```{r}
spikes <- names(spikes_from_sim(simulation))
GMR <- do.call(c,lapply(result_CV$TrainModel, function(nd) PESCAR:::pesca_FS(nd, newdata, y_samp, spikes, type = "PCR")[[1]]))

RV <- do.call(c,lapply(result_CV$TrainModel, function(modi){PESCAR:::RV_2(simulation[[5]], modi$outcome$A)}))

RV_y <- do.call(c,lapply(result_CV$TrainModel, function(modi){PESCAR:::RV_2(simulation[[5]][,c(3)], modi$outcome$A)}))
RV_X <- do.call(c,lapply(result_CV$TrainModel, function(modi){PESCAR:::RV_2(simulation[[5]][,-c(3)], modi$outcome$A)}))


lambda_y_vals_ <- lambda_y_vals


ux <- unique(lambda_vals)
uy <- unique(lambda_y_vals_)

r  <- (match(lambda_vals, ux) - 1) / max(length(ux) - 1, 1)
gr <- (match(lambda_y_vals_, uy) - 1) / max(length(uy) - 1, 1)
b  <- 0

col <- rgb(r, gr, b)

library(ggplot2)

# Create a data frame for result_CV and front data
result_CV_df <- data.frame(
  x = result_CV$cvErrors_mat[,1],
  y = result_CV$cvErrors_mat[,5],
  lambda_x = lambda_vals,
  lambda_y = lambda_y_vals,
  GMR = GMR,
  RV = RV,
  RV_X = RV_X,
  RV_y = RV_y,
  lambda_interaction = col
)


d <- result_CV_df
d <- cbind(d,c(1:nrow(d)))
D <- d[order(d[,1],d[,2],decreasing=FALSE),]
front_df <- D[which(!duplicated(cummin(D[,2]))),,drop = FALSE]

front_df <- data.frame(
  x = front_df[,1],
  y = front_df[,2]
)




library(ggplot2)
library(ggrepel)
library(patchwork)

## keep unique combinations in their current order
legend_df <- unique(result_CV_df[, c("lambda_x", "lambda_y", "lambda_interaction")])

## preserve order of appearance
legend_df$lambda_x_f <- factor(legend_df$lambda_x, levels = unique(legend_df$lambda_x))
legend_df$lambda_y_f <- factor(legend_df$lambda_y, levels = unique(legend_df$lambda_y))

x_lev <- levels(legend_df$lambda_x_f)
y_lev <- levels(legend_df$lambda_y_f)

x_lab <- rep("", length(x_lev))
y_lab <- rep("", length(y_lev))

x_lab[c(1, length(x_lev))] <- x_lev[c(1, length(x_lev))]
y_lab[c(1, length(y_lev))] <- y_lev[c(1, length(y_lev))]

p_leg <- ggplot(legend_df, aes(x = lambda_x_f, y = lambda_y_f, fill = lambda_interaction)) +
  geom_tile() +
  scale_fill_identity() +
  scale_x_discrete(labels = x_lab) +
  scale_y_discrete(labels = y_lab) +
  labs(x = expression(lambda[x]), y = expression(lambda[y])) +
  theme_bw(base_size = 8) +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1),
    axis.title = element_text(size = 8),
    plot.background = element_rect(fill = scales::alpha("white", 0.9), colour = "grey70")
  )
p_front_RV <- ggplot(result_CV_df, aes(x = x, y = y)) +
  geom_point(size = 5, aes(colour = I(lambda_interaction))) +
  geom_line(data = front_df, aes(x = x, y = y), color = "black") +
  ggrepel::geom_label_repel(
    data = result_CV_df[index_min_cv, , drop = FALSE],
    aes(label = "selected model"),
    inherit.aes = TRUE,
    fill = "white",
    label.size = 0.25,
    min.segment.length = 0
  ) +
  labs(x = "X fit", y = "Y fit") +
  theme_bw()

p_front <- p_front_RV +
  inset_element(
    p_leg,
    left   = 0.72,
    bottom = 0.56,
    right  = 0.98,
    top    = 0.98
  )

p_front
```



```{r}


legend_df <- expand.grid(
  lambda_x = sort(unique(result_CV_df$lambda_x)),
  lambda_y = sort(unique(lambda_y_vals_))
)


legend_df <- legend_df %>%
  mutate(
    r = log2(lambda_x + 1) / max(log2(result_CV_df$lambda_x + 1)),
    gr = log2(lambda_y + 1) / max(log2(lambda_y_vals_ + 1)),
    lambda_interaction = rgb(r, gr, 0)
  )

legend_plot <- ggplot(legend_df, aes(x = log2(lambda_x), y = log2(lambda_y), fill = lambda_interaction)) +
  geom_tile() +
  scale_fill_identity() +
  labs(x = expression(log[2](lambda[x])), 
       y = expression(log[2](lambda[y])),
       title = "IV Color Mapping") +
  theme_minimal(base_size = 75) +
  theme(plot.title = element_text(hjust = 0.5))

# ggsave("result_CV_lambda_colourmap.png")
```





```{r}
B <- PESCARmod$outcome$B
A <- PESCARmod$outcome$A


vx <- varimax(B)$rotmat  # R x R, orthogonal
A_rot <- A %*% vx
B_rot <- B %*% vx

A <- A_rot
B <- B_rot
# B <- center_columns_at_mode(B)

A <- A[,c(2,3,4,1,5,6)]
B <- B[,c(2,3,4,1,5,6)]

Coefs <- (solve(t(A)%*%A) %*% t(A) %*% y_samp) 
```

```{r}
Sigma <- PESCARmod$outcome$varExpPCs

Sigma <- Sigma[,c(2,3,4,1,5,6)]

###Component labelling and ordering:
mat <- Sigma[-c(nrow(Sigma)),]
# 
# # Function to get binary pattern and non-zero row indices
get_col_info <- function(col) {
  nz_idx <- which(col != 0)
  list(
    nz_count = length(nz_idx),
    pattern = paste(as.integer(col != 0), collapse = ""),
    row_str = paste(nz_idx, collapse = ",")
  )
}
# 
# #extract metadata for each column
col_info <- apply(mat, 2, get_col_info)
col_info_df <- do.call(rbind, lapply(seq_along(col_info), function(i) {
  data.frame(
    col_index = i,
    nz_count = col_info[[i]]$nz_count,
    pattern = col_info[[i]]$pattern,
    row_str = col_info[[i]]$row_str,
    stringsAsFactors = FALSE
  )
}))

#order columns: more non-zero values first, then by pattern
col_info_df <- col_info_df[order(-col_info_df$nz_count, col_info_df$pattern), ]




# Step 3: Assign structured labels
G_counter <- 0
LC_counters <- list()
D_counters <- list()
col_info_df$group <- NA_character_

for (i in seq_len(nrow(col_info_df))) {
  row <- col_info_df[i, ]
  
  if (row$nz_count == nrow(mat)) {
    # Fully dense (G)
    G_counter <- G_counter + 1
    col_info_df$group[i] <- paste0("C", G_counter)
    
  } else if (row$nz_count > 1) {
    # LC: sparse but more than one non-zero
    key <- row$row_str
    if (!key %in% names(LC_counters)) {
      LC_counters[[key]] <- 1
    } else {
      LC_counters[[key]] <- LC_counters[[key]] + 1
    }
    col_info_df$group[i] <- paste0("L", key, "_", LC_counters[[key]])
    
  } else if (row$nz_count == 1) {
    # D: exactly one non-zero
    key <- row$row_str  # this is just the row index, e.g. "1", "2", etc.
    if (!key %in% names(D_counters)) {
      D_counters[[key]] <- 1
    } else {
      D_counters[[key]] <- D_counters[[key]] + 1
    }
    col_info_df$group[i] <- paste0("D", key, "_", D_counters[[key]])
  }
}


col_info_df$Coef <- Coefs[col_info_df$col_index]

col_info_df$group[which(is.na(col_info_df$group))] <- 
  paste0("None",c(1:length(col_info_df$group[which(is.na(col_info_df$group))])))


```






```{r}

# 
B_y_ord <- B[,order(abs(Coefs), decreasing = T)]
A_y_ord <- A[,order(abs(Coefs), decreasing = T)]

Coefs_ord <- Coefs[order(abs(Coefs), decreasing = T)]/10


#loadings and VE plots here from PESCAR implementation on real data
df <- cbind.data.frame(do.call(c,lapply(Data,colnames)) ,do.call(c,lapply(Data,colnames)),rbind(B,t(Coefs)))

# do.call(c,lapply(Data,colnames))


colnames(df)[1:2] <- c("assay","Feature")


df$assay <- rep(names(Data), lapply(Data,ncol))


colnames(df)[-c(1,2)] <- paste0("PC",colnames(df)[-c(1,2)])




colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black")

# pdf(paste0(Sys.Date(),"_feature_loadings_project_full2.pdf"))
loadings <- ggplot(df, aes(x = PC1,y = PC2, colour = assay, alpha = 0.5)) +
  geom_point(alpha = 0.5) + 
  scale_color_manual(values = colours) +
  ggtitle("Loadings") +
  theme_bw()


data <- df

y1 <- Coefs   #_ord

  U <- df[]
  rownames(U) <- U$Feature
  U <- data.matrix(U[,-c(1,2)])

  
  UTP <- (dot(t(U),y1)/dot(y1,y1))
  
  UTP <- cbind.data.frame(names(UTP), UTP, U)
  
  ranked <- as.data.frame(UTP[order(abs(UTP$UTP), decreasing = T),])
  
  data$UTP   <- UTP[,2]



df_long <- data %>%
  pivot_longer(
    cols      = 3:(ncol(.) -1),       # columns with numeric data
    names_to  = "Component",     # new column for component name
    values_to = "Loading"        # new column for numeric values
  )


PESCA_lod_Struc_ggplot <- ggplot(df_long, 
                                 aes(x = Component, 
                                     y = Loading, 
                                     group = Feature,   # each row is a separate line
                                     color = assay, alpha = UTP)) +
  geom_line(, show.legend = FALSE) +
    geom_line(data = df_long[which(df_long$assay == "Y"),], alpha = 1, size = 1.5, show.legend = FALSE) +

  scale_color_manual(values = colours) +
  # labs(title = "PESCA", x = "Component", y = "Loading") +
  theme_ipsum() +  # Optional, from hrbrthemes
  theme(plot.title = element_text(size = 10)) +
  theme_void()

PESCA_lod_Struc_ggplot



```


```{r}

rank_UTP_matrix <- function(
  UTP_list,
  column = "UTP",
  data = NULL,
  n_top = NULL,          # legacy: if not NULL, uses abs top-n (per assay)
  quantile = 0.975,      # hard cutoff: keep <= 1-quantile OR >= quantile
  m_tail = 10,           # cap: at most m_tail positives + m_tail negatives per assay
  quantile_type = 8
) {

  process_one <- function(UTP_df) {

    UTP_split <- split(UTP_df, UTP_df$assay, drop = TRUE)

    ranked_list <- lapply(UTP_split, function(subdf) {

      vals <- suppressWarnings(as.numeric(subdf[[column]]))
      keep0 <- is.finite(vals)

      if (!any(keep0)) return(subdf[0, , drop = FALSE])

      # --- Legacy behavior: fixed top-n by abs value (per assay) ---
      if (!is.null(n_top)) {
        ord <- order(-abs(vals))
        out <- subdf[ord, , drop = FALSE]
        out <- out[seq_len(min(n_top, nrow(out))), , drop = FALSE]
        return(out[!is.na(out[[column]]), , drop = FALSE])
      }

      v <- vals[keep0]

      # --- Hard two-sided quantile cutoff on raw values ---
      q_hi <- max(0, min(1, quantile))
      q_lo <- 1 - q_hi

      thr_hi <- unname(quantile(v, probs = q_hi, na.rm = TRUE, type = quantile_type))
      thr_lo <- unname(quantile(v, probs = q_lo, na.rm = TRUE, type = quantile_type))

      elig <- keep0 & (vals >= thr_hi | vals <= thr_lo)
      out <- subdf[elig, , drop = FALSE]
      if (nrow(out) == 0L) return(out)

      # --- Cap to m_tail per sign (max 2*m_tail total), without changing thresholds ---
      m <- as.integer(m_tail)
      if (!is.na(m) && m > 0L) {

        pos <- out[out[[column]] > 0, , drop = FALSE]
        neg <- out[out[[column]] < 0, , drop = FALSE]

        if (nrow(pos) > 0) {
          pos <- pos[order(-pos[[column]]), , drop = FALSE]
          pos <- pos[seq_len(min(m, nrow(pos))), , drop = FALSE]
        }
        if (nrow(neg) > 0) {
          neg <- neg[order(neg[[column]]), , drop = FALSE]   # most negative first
          neg <- neg[seq_len(min(m, nrow(neg))), , drop = FALSE]
        }

        out <- rbind(pos, neg)
      }

      # final ordering by absolute magnitude (optional, but handy)
      out <- out[order(-abs(out[[column]])), , drop = FALSE]
      out
    })

    ranked <- do.call(rbind, ranked_list)
    ranked <- ranked[!is.na(ranked[[column]]), , drop = FALSE]
    ranked
  }

  if (is.data.frame(UTP_list)) {
    process_one(UTP_list)
  } else if (is.list(UTP_list)) {
    lapply(UTP_list, process_one)
  } else {
    stop("Input must be a data frame or list of data frames.")
  }
}

```

```{r}
 
  UTP$Feature <- data$Feature
    UTP$assay <- data$assay




```



```{r}
#for loop over all columns
columns <- colnames(UTP)[-1]

columns <- "UTP"

i <- NULL
for(i in 1:length(columns)){
  
  
  column <- columns[i]
  
  ranked <- rank_UTP_matrix(UTP,column = column,data,quantile = 0.75, m_tail = 40 )     #m_tail = 20
  

# data <- ranked

  # data$UTP   <- UTP[,2]
  data$UTP_sign <- ifelse(data[[column]] >= 0, "positive", "negative")

  
  
  
  #PUT data2 and df_long in function - for the sign creation 

# max_n <- n_top
data2 <- data %>%
  mutate(UTP_sign = ifelse(.data[[column]] >= 0, "positive", "negative")) %>%
  group_by(assay, UTP_sign) %>%
  mutate(
    rank_raw = rank(abs(.data[[column]]), ties.method = "first"),
    group_size = n(),
    rank_lin = ifelse(group_size > 1, (rank_raw - 1) / (group_size - 1), 0)
  ) %>%
  ungroup() %>%
  dplyr::select(-rank_raw, -group_size)

data2$rank_lin <- 0.9 * data2$rank_lin

df_long <- data2 %>%
  pivot_longer(
    cols      = 3:(ncol(data2) - 3),   
    names_to  = "Component",
    values_to = "Loading"
  )



df_long$Component <- factor(df_long$Component, levels = paste0("PC",c(1:ncol(B))))
df_long$UTP_sign <- factor(df_long$UTP_sign, levels = c("positive","negative"))


#some redundancy as gaps not used in plotting 


library(dplyr)
library(ggplot2)
library(hrbrthemes)

# 1. Join df_long with col_info_df to get the new Component labels
df_long$Component_num <- as.numeric(gsub("PC", "", df_long$Component))  # Extract index from PC1, PC2, etc.

df_long <- df_long %>%
  left_join(col_info_df %>% 
              dplyr::select(col_index, group, pattern), 
            by = c("Component_num" = "col_index")) %>%
  dplyr::rename(ComponentLabel = group)

pattern_split <- split(col_info_df$group, col_info_df$pattern)

# Step 2: Sort the patterns (binary interpreted as integer, descending)
sorted_patterns <- names(sort(sapply(names(pattern_split), function(p) strtoi(p, base = 2)), decreasing = TRUE))

# Step 3: Build component_levels with unique dummy gap labels
component_levels <- c()
gap_counter <- 1

for (p in sorted_patterns) {
  component_levels <- c(component_levels, pattern_split[[p]], paste0("__gap", gap_counter, "__"))
  gap_counter <- gap_counter + 1
}

# Remove trailing gap
component_levels <- head(component_levels, -1)

# Set ComponentLabel as factor with levels in order
df_long$ComponentLabel <- factor(df_long$ComponentLabel, levels = component_levels)

k <- 50
df_long$alpha_exp <- with(df_long, (exp(k * rank_lin) - 1) / (exp(k) - 1))


# colnames(df_long)[1] <- "Feature"

if(length(unique(df_long$Feature)) > length(unique(ranked$Feature))){
  df_long <- df_long[which(df_long$Feature %in% ranked$Feature),]

}



PESCA_lod_Struc_ggplot <- ggplot(df_long,
                                 aes(x = ComponentLabel,
                                     y = Loading,
                                     group = Feature,
                                     color = assay,
                                     alpha = alpha_exp,   #alpha_exp
                                     linetype = UTP_sign)) +
  geom_line(show.legend = FALSE) +
  geom_line(data = df_long[df_long$assay == "Y",], alpha = 1, size = 1.5, show.legend = FALSE) +   #, linetpe = 1
  scale_color_manual(values = colours) +
  facet_wrap(~ assay, scales = "free", ncol = 4) +
  labs(x = "Component") +
  theme_ipsum() +
  theme_bw() +
  theme(plot.title = element_text(size = 20),
        axis.text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        # axis.text.x = element_markdown(size = 14, angle = 45),
        strip.text = element_text(size = 24),
        axis.title = element_text(size = 24))





sigma <- log2(Sigma + 1)


# rownames(sigma) <- c(names(Data),"Full")

sigma <- sigma[,col_info_df$col_index]

colnames(sigma) <- col_info_df$group

max_val <- max(colSums(sigma[-which(rownames(sigma) == "X_full"),]))

rownames(sigma)[1:3] <- names(Data[1:3])

sigma <- reshape2::melt(t(sigma))


colnames(sigma)[1:2] <- c("Component","assay")

sigma <- sigma[-which(sigma$assay == "X_full"),]

levels(sigma$Component) <- col_info_df$group

# Stacked
r_VE <- ggplot(sigma, aes(fill=assay, y=value, x=Component)) + 
  scale_fill_manual(values = colours, guide = "none") +
  geom_bar(position="stack", stat="identity") + 
  coord_polar(start = 0) +
  theme_bw()+
  labs(title = "Variance Explained") +
  theme(axis.line=element_blank(), panel.border=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.text.x = element_text(size = 16),
      plot.title = element_text(hjust = 0.5, size = 24)) +  #,axis.text.x=element_blank()
  # theme_void() +
  ylab("")+
  xlab("") +
  ylim(-5,max_val)




# scaled_a <- wrap_elements(inset_element(blank, r_VE, left = 0.125, bottom = 0.125, right = 0.875, top = 0.875))
r_VE <- plot_spacer() +
  inset_element(r_VE,
                left = 0.05, bottom = 0.05, right = 0.95, top = 0.95,
                align_to = "panel")
# r_VE + PESCA_lod_Struc_ggplot 
r_VE + PESCA_lod_Struc_ggplot

ggsave(plot = r_VE + PESCA_lod_Struc_ggplot, file = paste0(column,"_PModShape_PESCAR.png"), width = 21, height = 9)

}


getwd()


```




# - HERE - 26_03_03




```{r}
df <- cbind.data.frame(do.call(c,lapply(Data,colnames)) ,do.call(c,lapply(Data,colnames)),rbind(B,t(Coefs)))

# do.call(c,lapply(Data,colnames))


colnames(df)[1:2] <- c("assay","Feature")


df$assay <- rep(names(Data), lapply(Data,ncol))


colnames(df)[-c(1,2)] <- paste0("PC",colnames(df)[-c(1,2)])


# colours = c("Gene" = "#A020F0", "Bacteria" = "#FFA500", "Metabolite" = "#55BB99", "Y" = "black")
# colours = c("Gene" = "blue", "Bacteria" = "yellow", "Metabolite" = "red", "Y" = "black")
colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black")


df_gg <- data.frame(
  # Flatten B by column
  x = c((B)),
  # Flatten the repeated Coefs by column
  y = c(matrix(rep(Coefs, nrow(B)), nrow = nrow(B), byrow = TRUE)),
  # Keep track of which column each point came from
  col_index = rep(1:ncol(B), each = nrow(B))
)

feature_vec <- do.call(c, lapply(Data[1:3], colnames))
assay_vec   <- rep(names(Data)[1:3], times = lapply(Data[1:3], ncol))

length(feature_vec)  
length(assay_vec)   

df_gg$Feature <- rep(feature_vec, ncol(B))
df_gg$assay   <- rep(assay_vec,    ncol(B))


head(df_gg)


y1 <- Coefs

  U <- df[!df$assay == "Y", ]
  rownames(U) <- U$Feature
  U <- data.matrix(U[,-c(1,2)])

  
  UTP <- (dot(t(U),y1)/dot(y1,y1))
  
  UTP <- cbind.data.frame(names(UTP), UTP, U)
  
  ranked <- as.data.frame(UTP[order(abs(UTP$UTP), decreasing = T),])
  
  df_gg$UTP   <- rep(UTP[,2],    ncol(B))

library(ggplot2)

p_coef_ord <- ggplot(df_gg, aes(x = y, y = x, color = assay, alpha = UTP)) +
  # geom_point() +
  labs(
    # color = "Column",
    x = "Features",
    y = "Component Coefficient"
  ) +
  geom_line(aes( group = Feature)) +
  scale_alpha_continuous() +
    # geom_line(data = df_long[which(df_long$assay == "Y"),], alpha = 1, size = 2, show.legend = FALSE) +   # Baits here

  scale_color_manual(values = colours) +
  # labs(title = "PESCA", x = "Component", y = "Loading") +
  # theme_ipsum() +  # Optional, from hrbrthemes
geom_abline(intercept = 0, slope = 1, size = 2) +
  theme_minimal()

# p_coef_ord

```


```{r}

data <- log2(PESCARmod$outcome$varExpPCs[,order(abs(Coefs), decreasing = T)] + 1)

colnames(data) <- paste0("PC",1:ncol(data))

rownames(data) <- c(names(Data)[1:3],"Full")



max_val <- max(colSums(data[-which(rownames(data) == "Full"),]))

data <- melt(t(data))
# colours2 <- c(colours, "Full" = "yellow")



colnames(data)[1:2] <- c("Component","assay")

data <- data[-which(data$assay == "Full"),]

# Stacked
r_VE <- ggplot(data, aes(fill=assay, y=value, x=Component)) + 
  scale_fill_manual(values = colours, guide = "none") +
    geom_bar(position="stack", stat="identity") + 
  coord_polar(start = 0) +
  theme_bw()+
  theme(axis.line=element_blank(), panel.border=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank()) +  #,axis.text.x=element_blank()
  # theme_void() +
  ylab("")+
  xlab("") +
  ylim(-5,max_val) + theme_void()

```















```{r}
# Data_model_df <- A %*% t(B)

Data_model_df <- A %*% t(B)    # data model y related


colnames(Data_model_df) <- do.call(c, lapply(Data[1:3], colnames))

y_model <- do.call(cbind,Data[1:3]) %*% PESCARmod$outcome$W_k %*% Coefs

Data_model <- list(Data)

colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black")



Data_model <- lapply(
  do.call(c,lapply(Data, function(i) unique(gsub("_.*","",colnames(i))))),
  function(p) Data_model_df[, grep(p, colnames(Data_model_df)), drop = FALSE]
)

ch <- ggplot(melt(Data_model[[1]]), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#11AA00", high = "black", low = "white", guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines')) 


gh <- ggplot(melt(Data_model[[2]]), aes(x = Var2, y = Var1, fill = value)) + 
  geom_tile() + 
  scale_fill_gradient2(mid = "#0011FF", high = "black", low = "white", guide="none") + 
  theme_void() + 
  theme(
    plot.margin = unit(c(0,0.2,0,1), "lines"))


bh <- ggplot(melt(Data_model[[3]]), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#FB0000", high = "black", low = "white",guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines'))


yh <- ggplot(melt(y_model), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#002060", high = "black", low = "white",guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines'))


# (bh + plot_spacer()) + (gh + plot_spacer()) + ch + yh

p11 <- ggarrange(ch, gh, bh, yh, nrow = 1, widths = c(4,4,4,1))

```




```{r}
library(igraph)
library(dplyr)
library(tidyr)
library(tidygraph)
library(lubridate)
# library(iterpc)
library(ggraph)
library(tidygraph)

set.seed(123)
B_y_ord <- B[,order(abs(Coefs), decreasing = T)]

colnames(B_y_ord) <- paste0("PC",1:ncol(B_y_ord))

# cor_matrix <- as.matrix(cor(rbind(B,t(Coefs))))
cor_matrix <- as.matrix(cor(B_y_ord))

Coefs_ord <- Coefs[order(abs(Coefs), decreasing = T)]

cor_matrix <- cbind(Coefs_ord, cor_matrix)
cor_matrix <- rbind(c(1,Coefs_ord), cor_matrix)

cor_matrix[lower.tri(cor_matrix)] <- t(cor_matrix)[lower.tri(cor_matrix)]
# Set diagonal to 1 (typical for correlation)
diag(cor_matrix) <- 1

cor_matrix[which(is.na(cor_matrix))] <- 0

colnames(cor_matrix) <- c("Y",paste0("PC",c(1:opts$R)))

# # 2. Create or load metadata (matching the number of nodes)
# metadata <- data.frame(
#   node_id = paste0("Sample_", 1:5),
#   condition = c("Control", "Control", "Treatment", "Treatment", "Control")
# )

# 3. Convert the correlation matrix into an igraph object
#    We'll treat the correlation as a weighted adjacency matrix.
#    Set diag = FALSE to avoid self-loops (which have weight = 1 on the diagonal).
g <- graph_from_adjacency_matrix(
  cor_matrix,
  mode = "undirected",
  weighted = TRUE,
  diag = FALSE
)

# 4. Add node attributes from the metadata
# V(g)$name <- metadata$node_id
# 


#rgb combination example from:
#https://stackoverflow.com/questions/11306075/how-to-create-rgb-image-from-three-matrices-in-r

# r <- PESCARmod$outcome$varExpPCs[1,]/colSums(PESCARmod$outcome$varExpPCs[1:3,])
# gr <- PESCARmod$outcome$varExpPCs[2,]/colSums(PESCARmod$outcome$varExpPCs[1:3,])
# b <- PESCARmod$outcome$varExpPCs[3,]/colSums(PESCARmod$outcome$varExpPCs[1:3,])


x <- PESCARmod$outcome$varExpPCs[,order(abs(Coefs), decreasing = T)]
# x <- sweep(x, 1, pmax(1, ncol(x) - rowSums(x != 0)), FUN = "/")

SCALLY_WAH <- function(i){i/max(abs(i))}


x1 <- sweep(x, 1, pmax(1, ncol(x) - rowSums(x != 0)), FUN = "/")
x1 <- x1[1:3,]
x1 <- apply(x1[,],2,SCALLY_WAH)
x1[which(is.na(x1))] <- 0
x1[x1<0] <- 0





# "#76557A" "#6B5575" "#88558D" "#FF00F2" "#FA00FF" "#FF00DB" "#002060"
r <- x1[3,]
gr <- x1[1,]
b <- x1[2,]

col <- rgb(r, gr, b)
dim(col) <- dim(r)

col <- c("#002060", col)

# V(g)$group <- c(rep(c("Gene","Metabolite","Bacteria"), each = 10), "Phenotype")    #define CLD here   - HERE -
# 
# 
V(g)$colour <- col  #c(rep(c("#A020F0","#00B050","#FFA500"), each = 10), "#002060")   # use CLD for this too



threshold <- 0.1     # - WARNING -

g <- delete_edges(g, E(g)[abs(weight) < threshold])

g <- delete_vertices(simplify(g), degree(g)==0)

edge_weights <- E(g)$weight
edge_colors  <- ifelse(edge_weights > 0, "red", "blue")

E(g)$weight <- abs(E(g)$weight)

E(g)$colour <- edge_colors
#make vertex_size vector 

set.seed(125)
# 7. Plot the graph
plot(
  g,
  layout = layout_with_kk(g),
  # vertex.label       = V(g)$name,
  vertex.color       = V(g)$colour,
  vertex.size        = 15,
  vertex.label = NA,
  edge.width         = abs(edge_weights) ,  # scale by absolute correlation
  edge.color         = edge_colors
)

# "#3D833F" "#39883E" "#417A44" "#83007C" "#7E0081" "#890076" "#002060"

V(g)$shape <- gsub("\\d$","",names(V(g)))


tg <- as_tbl_graph(g)
```




```{r}
#create layout matrix - HERE -

p <- ggraph(tg, layout = "kk") + 

  geom_edge_link(aes(edge_width = weight, color = I(colour))) +
  
  # Draw nodes, mapping their color from V(g)$colour
  geom_node_point(aes(color = I(colour), shape = shape), size = 0) +

  # Optionally label the nodes:
  # geom_node_text(aes(label = name), repel = TRUE, color = "black") +

  # Some theme settings
  theme_void() +
  # Possibly override scale for edge_width
  scale_edge_width(range = c(0.5, 1), guide = "none") +
  scale_shape_discrete(guide = "none")

# p

# "#002060" "#409DFF" "#C5FFA9" "#07FFB9" "#07F2FF" "#FF617B"

```

```{r}

library(ggraph)
library(tidygraph)
library(igraph)
library(ggplot2)

set.seed(124) # - WARNING -


layout_data <- create_layout(tg, layout = "kk")


col <- V(g)$colour
         

offset <- 0.15

i <- NULL
for (i in seq_len(nrow(layout_data))) {
  x_i <- layout_data$x[i]
  y_i <- layout_data$y[i]

  if(i == 1){
    
    mat <- as.matrix(y_model)
    
  }else{
    
    # mat <- A[,(i - 1)] %*% t(B[,(i - 1)])
    
        mat <- as.matrix(A_y_ord[,(i - 1)])

    
  }
  # Scale to [0,1]
  mat_scaled <- (mat - min(mat)) / (max(mat) - min(mat))

  # Build a color palette and index into it
  pal <- colorRampPalette(c("white",col[i],"black"))(256)
  # Convert numeric values into actual color strings
  mat_colors <- pal[as.integer(mat_scaled * 255) + 1]

  # Reshape 'mat_colors' into the same dimension as 'mat'
  mat_colors <- matrix(mat_colors, nrow = nrow(mat), ncol = ncol(mat))

  # Now we can add an annotation_raster layer for that matrix of color strings
  p <- p + annotation_raster(
    raster = mat_colors,
    xmin   = x_i - offset, xmax = x_i + offset,
    ymin   = y_i - offset, ymax = y_i + offset,
    interpolate = FALSE  # TRUE could look good 
  ) 
 
}

p <- p +
    geom_node_text(aes(label = name), 
                 repel = TRUE,    # keep labels from overlapping 
                 color = "black")
 


x_range <- range(layout_data$x)
 y_range <- range(layout_data$y)
 
 # offset <- 0.3
 
 p <- p + coord_cartesian(
     xlim = c(x_range[1] - offset, x_range[2] + offset),
     ylim = c(y_range[1] - offset, y_range[2] + offset),
     clip = "off"
 )
 
 # 7) Optionally add some plot margin so nothing is clipped by the plot boundary
 p <- p + theme(
     plot.margin = unit(c(1,1,1,1), "cm")
 ) #
 print(p)

```

```{r}

 df <- as.data.frame(simulation[[5]], stringsAsFactors = FALSE)
  df$sample <- seq_len(nrow(df))


 long <- as.data.frame(df) %>%
    pivot_longer(cols = -c(sample),
                 names_to = "series",
                 values_to = "value")



p1 <- ggplot(long, aes(x = sample, y = value, color = series, group = series)) +
     geom_line() +
     # geom_point() +
     # labs(x = xlab, y = ylab, color = "Series", title = title) +
     theme_minimal(base_size = 13)
 


 df <- as.data.frame(A_rot, stringsAsFactors = FALSE)
  df$sample <- seq_len(nrow(df))


 long <- as.data.frame(df) %>%
    pivot_longer(cols = -c(sample),
                 names_to = "series",
                 values_to = "value")



p2 <- ggplot(long, aes(x = sample, y = value, color = series, group = series)) +
     geom_line() +
     # geom_point() +
     # labs(x = xlab, y = ylab, color = "Series", title = title) +
     theme_minimal(base_size = 13)
 

p1 + p2

```

<!-- - HERE - -->



<!-- ```{r} -->
<!-- Sigma <- matrix(c(0.5 , 0.5 , 0.1 , 0.5 , 0.5 , 0 , -->
<!--                   0.5 , 0.5 , 0.1 , 0.5 , 0   , 0 , -->
<!--                     0 , 0.5 , 0.1 , 0   , 0   , 0), byrow = T, nrow = 3) -->


<!-- ((PESCA_lod_Struc_ggplot + r_VE)/       #p_coef_ord -->
<!--   p11) + (p)  # + cube_plot) -->

<!-- plottings <- FALSE -->
<!-- if(plottings == TRUE){ -->
<!--   ggsave(paste0(Sys.Date(),"_PESCAR_",alpha,"_",opts$R,"_comp.tiff")) -->

<!-- } -->
<!-- ``` -->



<!-- ```{r} -->
<!-- rownames(B) <- c(do.call(c,lapply(Data[1:3], colnames))) -->

<!-- GC <- ranked[grep("^G",rownames(ranked)),] -->
<!-- CC <- ranked[grep("^C",rownames(ranked)),] -->
<!-- BC <- ranked[grep("^B",rownames(ranked)),] -->



<!-- gene_cands <- GC[order(abs(GC$UTP)),] -->
<!-- met_cands <- CC[order(abs(CC$UTP)),] -->
<!-- mic_cands <- BC[order(abs(BC$UTP)),] -->




<!-- cands <- c(gene_cands[1:10,1], met_cands[1:10,1], mic_cands[1:10,1]) -->



<!-- d4net <- rbind(B[cands,], t(Coefs)) -->


<!-- ``` -->


<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- library(tidygraph) -->
<!-- library(lubridate) -->
<!-- # library(iterpc) -->
<!-- library(igraph) -->
<!-- library(igraph) -->


<!-- set.seed(123) -->
<!-- cor_matrix <- as.matrix(cor(t(d4net))) -->



<!-- cor_matrix[lower.tri(cor_matrix)] <- t(cor_matrix)[lower.tri(cor_matrix)] -->
<!-- # Set diagonal to 1 (typical for correlation) -->
<!-- diag(cor_matrix) <- 1 -->
<!-- cor_matrix[which(is.na(cor_matrix))] <- 0 -->

<!-- # # 2. Create or load metadata (matching the number of nodes) -->
<!-- # metadata <- data.frame( -->
<!-- #   node_id = paste0("Sample_", 1:5), -->
<!-- #   condition = c("Control", "Control", "Treatment", "Treatment", "Control") -->
<!-- # ) -->

<!-- # 3. Convert the correlation matrix into an igraph object -->
<!-- #    We'll treat the correlation as a weighted adjacency matrix. -->
<!-- #    Set diag = FALSE to avoid self-loops (which have weight = 1 on the diagonal). -->
<!-- g <- graph_from_adjacency_matrix( -->
<!--   cor_matrix, -->
<!--   mode = "undirected", -->
<!--   weighted = TRUE, -->
<!--   diag = FALSE -->
<!-- ) -->

<!-- # 4. Add node attributes from the metadata -->
<!-- # V(g)$name <- metadata$node_id -->
<!-- V(g)$group <- c(rep(c("X2","X1","X3"), each = 10), "Phenotype") -->
<!-- V(g)$color <- c(rep(c("#A020F0","#00B050","#FFA500"), each = 10), "#002060") -->




<!-- threshold <- 0.5 -->

<!-- # Remove edges whose absolute weight is below that threshold -->
<!-- g <- delete_edges(g, E(g)[abs(weight) < threshold]) -->


<!-- edge_weights <- E(g)$weight -->
<!-- edge_colors  <- ifelse(edge_weights > 0, "red", "blue") -->

<!-- E(g)$weight <- abs(E(g)$weight) -->


<!-- #make vertex_size vector  -->

<!-- set.seed(123) -->
<!-- # 7. Plot the graph -->
<!-- plot( -->
<!--   g, -->
<!--   layout = layout_with_kk(g), -->
<!--   # vertex.label       = V(g)$name, -->
<!--   vertex.color       = V(g)$color, -->
<!--   vertex.size        = 15, -->
<!--   vertex.label = NA, -->
<!--   edge.width         = abs(edge_weights) ,  # scale by absolute correlation -->
<!--   edge.color         = edge_colors -->
<!-- ) -->

<!-- ``` -->







<!-- ```{r} -->
<!-- spike_vals <- spikes_from_sim(simulation) -->
<!-- spikes <- names(spikes_from_sim(simulation)) -->

<!-- cands <-  pesca_FS(PESCAmodel = PESCARmod, Data = Data[1:3], y = y_samp, spikes = spikes,type = "PCR")[[2]] -->

<!-- # cands2 <- diag(c(Coefs)) %*% t(B) -->

<!-- cands <- cbind.data.frame("ID" = rownames(cands), cands) -->
<!-- cands <- cands[order(cands[,2],decreasing = T), ,drop = FALSE] -->

<!-- which(cands$ID %in% spikes) -->
<!-- cands[which(cands$ID %in% spikes),] -->


<!-- plot( simulation[[2]] %*% Yweights) -->
<!-- plot(B %*% Coefs) -->

<!-- cor(simulation[[2]] %*% Yweights, B %*% Coefs)  # - Use this for alpha - plus label as spikes  -->

<!--  t(simulation[[2]] %*% Yweights) %*%  (B %*% Coefs) -->

<!--                                                 # make comp_weights into a matrix and fill rest with zeroes -->

<!-- ``` -->

<!-- - HERE - -->
<!-- runto -->


<!-- ```{r} -->
<!-- #  -->
<!-- iteration_df <- bind_rows( -->
<!--   lapply(seq_along(result_CV$TrainModel), function(d) { -->
<!--     # pull out the k losses for model d -->
<!--     loss_vals <- sapply(result_CV$TrainModel[[d]]$loss, `[[`, "loss") -->
<!--     data.frame( -->
<!--       run_id    = d, -->
<!--       iteration = seq_along(loss_vals), -->
<!--       loss      = loss_vals -->
<!--     ) -->
<!--   }) -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # iteration_df_wip <- map_dfr( -->
<!-- #   seq_along(result_CV$TrainModel),  # for each random start d -->
<!-- #   function(d) { -->
<!-- #     mdl   <- result_CV$TrainModel[[d]] -->
<!-- #     loss_vals <- map_dbl(mdl$loss, "loss") -->
<!-- #     A_list    <- mdl$A     # must be a list of matrices of same length -->
<!-- #     rv_vals   <- map_dbl(A_list, ~ RV_2(simulation[[5]], .x)) -->
<!-- #      -->
<!-- #     # assemble into a tibble -->
<!-- #     tibble( -->
<!-- #       run_id    = d, -->
<!-- #       iteration = seq_along(loss_vals), -->
<!-- #       loss      = loss_vals, -->
<!-- #       RV        = rv_vals -->
<!-- #     ) -->
<!-- #   } -->
<!-- # ) -->

<!-- pfs <- function(A, B, Data, y, spikes = NULL, type = c("yasblock","PCR")){ -->

<!--   stp <- t(A) %*% y -->

<!--   if(type == "PCR"){ -->
<!--     scaled_lods <- B %*% stp -->
<!--     rownames(scaled_lods) <- colnames(do.call(cbind,Data))[] -->


<!--   }else{ -->
<!--     scaled_lods <- B %*% stp -->
<!--     rownames(scaled_lods) <- colnames(do.call(cbind,Data))[-nrow(B)] -->

<!--   } -->



<!--   cands <- scaled_lods[order(abs(scaled_lods[,1]), decreasing = T),] -->

<!--   if(!is.null(spikes)){ -->
<!--     RP <- prod(which(names(cands) %in% spikes))^(1/length(spikes)) -->

<!--   } -->
<!-- } -->



<!-- nModels <- length(result_CV$TrainModel) -->
<!-- out_list <- vector("list", nModels) -->

<!-- for (d in seq_len(nModels)) { -->
<!--   mdl <- result_CV$TrainModel[[d]] -->
<!--   K   <- length(mdl$loss)        # number of iterations for model d -->

<!--   # pre-allocate vectors -->
<!--   loss_vec <- numeric(K) -->
<!--   rv_vec   <- numeric(K) -->
<!--   gmr_vec <- numeric(K) -->
<!--   # fill them -->
<!--   for (k in seq_len(K)) { -->
<!--     loss_vec[k] <- mdl$loss[[k]]$loss -->
<!--     rv_vec[k]   <- RV_2(simulation[[5]], mdl$A[[k]]) -->
<!--     gmr_vec[k] <- pfs(mdl$A[[k]], mdl$B[[k]], newdata, y_samp, spikes, type = "PCR")[[1]] -->
<!--   } -->

<!--   # assemble into a tiny data.frame -->
<!--   out_list[[d]] <- data.frame( -->
<!--     run_id    = d, -->
<!--     iteration = seq_len(K), -->
<!--     loss      = loss_vec, -->
<!--     RV        = rv_vec, -->
<!--     GMR       = gmr_vec -->
<!--   ) -->
<!-- } -->

<!-- # row-bind them all together -->
<!-- iteration_df_wip <- do.call(rbind, out_list) -->
<!-- rownames(iteration_df) <- NULL -->


<!-- ``` -->


<!-- ```{r} -->

<!-- library(dplyr) -->

<!-- # Identify best run by final (max iteration) loss -->
<!-- best_run <- index_min_cv -->

<!-- # Plot all runs (faint) and overlay best run (bold/red) -->
<!-- p2 <- ggplot(iteration_df_wip[,], aes(x = iteration, y = RV, group = run_id)) + -->
<!--   geom_line(alpha = 0.2) + -->
<!--   geom_line( -->
<!--     data    = filter(iteration_df_wip[,], run_id == best_run), -->
<!--     aes(colour = "Best run"), -->
<!--     size    = 1 -->
<!--   ) + -->
<!--   scale_colour_manual("", values = "steelblue") + -->
<!--   theme_minimal() + -->
<!--   labs( -->
<!--     title = "", -->
<!--     x     = "Iteration", -->
<!--     y     = "RV" -->
<!--   ) + -->
<!--   theme( -->
<!--     plot.title      = element_text(hjust = 0.5), -->
<!--     legend.position = "top" -->
<!--   ) -->

<!-- p3 <- ggplot(iteration_df_wip[,], aes(x = iteration, y = log2(GMR), group = run_id)) + -->
<!--   geom_line(alpha = 0.2) + -->
<!--   geom_line( -->
<!--     data    = filter(iteration_df_wip[,], run_id == best_run), -->
<!--     aes(colour = "Best run"), -->
<!--     size    = 1 -->
<!--   ) + -->
<!--   scale_colour_manual("", values = "steelblue") + -->
<!--   theme_minimal() + -->
<!--   labs( -->
<!--     title = "", -->
<!--     x     = "Iteration", -->
<!--     y     = "GMR" -->
<!--   ) + -->
<!--   theme( -->
<!--     plot.title      = element_text(hjust = 0.5), -->
<!--     legend.position = "top" -->
<!--   ) -->

<!-- p2 + p3 -->
<!-- ggsave("RV_GMR_75.png") -->
<!-- ``` -->


<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(ggplot2) -->

<!-- # compute a scale factor so that GMR*sf is on the same scale as RV -->
<!-- max_RV  <- 1 #max(iteration_df_wip$RV,  na.rm = TRUE) -->
<!-- max_GMR <- max(iteration_df_wip$GMR, na.rm = TRUE) -->
<!-- sf      <- max_RV / max_GMR -->

<!-- # build the plot -->
<!-- p <- ggplot(iteration_df_wip, aes(x = iteration, group = run_id)) + -->

<!--   # all RV traces (faint) -->
<!--   # geom_line(aes(y = RV), alpha = 0.2, colour = "grey50") + -->
<!--   # highlight best_run RV -->
<!--   geom_line( -->
<!--     data = filter(iteration_df_wip, run_id == best_run), -->
<!--     aes(y = RV), colour = "steelblue", size = 1.1 -->
<!--   ) + -->

<!--   # all GMR traces, *scaled* (faint) -->
<!--   # geom_line(aes(y = GMR * sf), alpha = 0.2, colour = "grey50", linetype = "dashed") + -->
<!--   # highlight best_run GMR (scaled) -->
<!--   geom_line( -->
<!--     data = filter(iteration_df_wip, run_id == best_run), -->
<!--     aes(y = GMR * sf), colour = "firebrick", size = 1.1, linetype = "dashed" -->
<!--   ) + -->

<!--   # primary y-axis for RV, secondary for GMR -->
<!--   scale_y_continuous( -->
<!--     name    = "RV", -->
<!--     sec.axis = sec_axis(~ . / sf, name = "GMR")  # invert the scaling -->
<!--   ) + -->

<!--   scale_x_continuous("Iteration") + -->
<!--   theme_minimal() + -->
<!--   theme( -->
<!--     axis.title.y.left   = element_text(color = "steelblue", size=12), -->
<!--     axis.title.y.right  = element_text(color = "firebrick", size=12), -->
<!--     legend.position     = "none" -->
<!--   ) + -->
<!--   labs( -->
<!--     title = "Iteration Traces: RV (solid) vs. GMR (dashed)"#, -->
<!--     # subtitle = sprintf("Best run highlighted: run_id = %s", best_run) -->
<!--   ) -->

<!-- print(p) -->
<!-- ggsave("RV_GMR_75_comb.png", bg = "white") -->
<!-- ``` -->






<!-- ```{r} -->
<!-- A_true <- simulation[[5]] -->

<!-- angle_df <- bind_rows( -->
<!--   lapply(seq_along(PESCARmod$A), function(k) { -->
<!--     M  <- t(A_true) %*% PESCARmod$A[[k]]    # r×r -->
<!--     s  <- svd(M, nu=0, nv=0)$d             # singular values σ₁…σr -->
<!--     theta <- acos(pmin(pmax(s, -1), 1))    # principal angles in radians -->
<!--     data.frame( -->
<!--       Iteration = k, -->
<!--       Component = factor(1:length(theta)), -->
<!--       Angle      = theta -->
<!--     ) -->
<!--   }) -->
<!-- ) -->



<!-- # ggplot(angle_df, aes(x = Iteration, y = Angle, color = Component)) + -->
<!-- #   geom_line(size = 0.8) + -->
<!-- #   geom_point(size = 1.5) + -->
<!-- #   labs( -->
<!-- #     title    = "Principal Angles vs. Iteration", -->
<!-- #     subtitle = "Each line shows θ_j^(k) for component j", -->
<!-- #     x        = "Iteration k", -->
<!-- #     y        = expression(theta[j]^(k)), -->
<!-- #     color    = "Component j" -->
<!-- #   ) + -->
<!-- #   theme_minimal() + -->
<!-- #   theme( -->
<!-- #     legend.position = "right", -->
<!-- #     panel.grid.minor = element_blank() -->
<!-- #   ) -->

<!-- # 2) make a heatmap -->
<!-- p_heat <- ggplot(angle_df, aes(x = Iteration, y = Component, fill = Angle)) + -->
<!--   geom_tile() + -->
<!--   scale_fill_viridis_c(option = "magma", direction = -1) + -->
<!--   labs( -->
<!--     title = "Principal Angles: True vs. Estimated Subspaces", -->
<!--     x = "Iteration k", y = "Component r", -->
<!--     fill = expression(theta[r]^(k)) -->
<!--   ) + -->
<!--   theme_minimal() -->

<!-- p_heat -->

<!-- ``` -->





<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- library(ggplot2) -->

<!-- # 1) Compute all principal angles θ_j^(k) -->
<!-- angle_df <- bind_rows( -->
<!--   lapply(seq_along(PESCARmod$A), function(k) { -->
<!--     M     <- t(A_true) %*% PESCARmod$A[[k]]  # r×r -->
<!--     sigma <- svd(M, nu=0, nv=0)$d            # σ₁…σr -->
<!--     theta <- acos(pmin(pmax(sigma, -1), 1))  # θ₁…θr -->
<!--     data.frame( -->
<!--       Iteration = k, -->
<!--       Component = factor(1:length(theta)), -->
<!--       Theta     = theta -->
<!--     ) -->
<!--   }) -->
<!-- ) -->

<!-- # 2) Normalize per‐component into [0,1] by improvement fraction -->
<!-- angle_df <- angle_df %>% -->
<!--   group_by(Component) %>% -->
<!--   mutate( -->
<!--     Delta = (first(Theta) - Theta) / first(Theta), -->
<!--     # Map improvement to an angular span [0, π] -->
<!--     Phi   = pi * Delta -->
<!--   ) %>% -->
<!--   ungroup() -->

<!-- # 3) Compute end‐points of each ray on the unit circle -->
<!-- angle_df <- angle_df %>% -->
<!--   mutate( -->
<!--     xend = cos(Phi), -->
<!--     yend = sin(Phi) -->
<!--   ) -->

<!-- r <- ncol(A_true) -->

<!-- # build a df of true‐arrows: all from (0,0) to angle=pi, radius=1 -->
<!-- true_arrow_df <- data.frame( -->
<!--   Component = factor(1:r), -->
<!--   x        = 0,  -->
<!--   y        = 0, -->
<!--   xend     = cos(pi),  -->
<!--   yend     = sin(pi) -->
<!-- ) -->


<!-- # 4) Plot: one facet per component, rays colored by iteration -->
<!-- p_ray <- ggplot(angle_df, aes(x = 0, y = 0)) + -->
<!--   geom_segment(aes(xend = xend, yend = yend, color = Iteration), -->
<!--                size = 0.7, arrow = arrow(length = unit(0.15, "cm"))) + -->
<!--   coord_equal() + -->
<!--   facet_wrap(~ Component, ncol = 3) + -->
<!--   scale_color_viridis_c(option = "plasma") + -->
<!--   labs( -->
<!--     title = "Convergence Rays: Relative Principal Angle Improvement", -->
<!--    # subtitle = "Each ray for k goes to angle φ = π·((θ₁–θₖ)/θ₁)", -->
<!--     x = NULL, y = NULL, color = "Iter k" -->
<!--   ) + -->
<!--   geom_segment( -->
<!--     data = true_arrow_df, -->
<!--     aes(x = x, y = y, xend = xend, yend = yend), -->
<!--     color = "black", -->
<!--     size  = 1.5, -->
<!--     arrow = arrow(length = unit(0.3, "cm")) -->
<!--   ) + -->
<!--   theme_minimal() + -->
<!--   theme( -->
<!--     axis.text  = element_blank(), -->
<!--     axis.ticks = element_blank(), -->
<!--     panel.grid = element_blank() -->
<!--   ) -->

<!-- p_ray -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p/ -->
<!--   p_heat/ -->
<!--   p_ray -->

<!-- ``` -->


<!-- ```{r} -->
<!-- # install.packages(c("dplyr","tidyr","purrr","ggplot2"))  # if needed -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- library(purrr) -->
<!-- library(ggplot2) -->

<!-- # --- 1) Extract to a long data frame ----------------------------------------- -->
<!-- loss_list <- PESCARmod$loss -->
<!-- D <- length(loss_list[[1]]$f_obj_per_dataset)  # number of datasets -->

<!-- df <- imap_dfr(loss_list, function(Lk, k) { -->
<!--   # per-dataset vectors -->
<!--   fdat <- tibble( -->
<!--     iter = k, -->
<!--     metric = "f_obj_per_dataset", -->
<!--     dataset = paste0("X", seq_len(D)), -->
<!--     value = as.numeric(Lk$f_obj_per_dataset) -->
<!--   ) -->
<!--   gdat <- tibble( -->
<!--     iter = k, -->
<!--     metric = "g_obj_per_dataset", -->
<!--     dataset = paste0("X", seq_len(D)), -->
<!--     value = as.numeric(Lk$g_obj_per_dataset) -->
<!--   ) -->
<!--   # scalars (tag with special dataset labels) -->
<!--   y_rmse <- tibble(iter = k, metric = "y_RMSE",      dataset = "Y",       value = as.numeric(Lk$y_RMSE)) -->
<!--   glasso <- tibble(iter = k, metric = "group_lasso", dataset = "penalty", value = as.numeric(Lk$group_lasso)) -->

<!--   Total <- tibble(iter = k, metric = "Total",      dataset = "All",       value = as.numeric(Lk$loss)) -->

<!--   Y <- tibble(iter = k, metric = "Y",      dataset = "Y",       value = as.numeric(Lk$y_obj_full)) -->
<!--   X <- tibble(iter = k, metric = "X",      dataset = "X",       value = as.numeric(Lk$X_obj_full)) -->

<!--   bind_rows(fdat, gdat, y_rmse, glasso, Total, Y, X) -->
<!-- }) -->



<!-- df_scaled <- df %>% -->
<!--   group_by(metric) %>% -->
<!--   mutate(scaled = (value - min(value, na.rm=TRUE)) / (max(value, na.rm=TRUE) - min(value, na.rm=TRUE))) %>% -->
<!--   ungroup() -->




<!-- ploss1 <- ggplot(df_scaled[which(df_scaled$metric %in% c("Total")),], aes(x = iter, -->
<!--                       y = scaled, -->
<!--                       color = metric, -->
<!--                       linetype = dataset, -->
<!--                       group = interaction(metric, dataset))) + -->
<!--   geom_line() + -->
<!--   geom_point(alpha = 0.5, size = 1) + -->
<!--   scale_linetype_discrete(name = "Dataset") + -->
<!--   labs(x = "Iteration (k)", -->
<!--        y = "Scaled loss", -->
<!--        color = "Metric", -->
<!--        title = "Total Loss") + -->
<!--   theme_minimal() -->

<!-- ploss2 <- ggplot(df_scaled[which(df_scaled$metric %in% c("X","Y")),], aes(x = iter, -->
<!--                       y = scaled, -->
<!--                       color = metric, -->
<!--                       linetype = dataset, -->
<!--                       group = interaction(metric, dataset))) + -->
<!--   geom_line() + -->
<!--   geom_point(alpha = 0.5, size = 1) + -->
<!--   scale_linetype_discrete(name = "Dataset") + -->
<!--   labs(x = "Iteration (k)", -->
<!--        y = "Scaled loss", -->
<!--        color = "Metric", -->
<!--        title = "X and Y Loss") + -->
<!--   theme_minimal() -->


<!-- # --- 3) Single plot ---------------------------------------------------------- -->
<!-- ploss3 <-ggplot(df_scaled[-which(df_scaled$metric %in% c("Total","X","Y")),], aes(x = iter, -->
<!--                       y = scaled, -->
<!--                       color = metric, -->
<!--                       linetype = dataset, -->
<!--                       group = interaction(metric, dataset))) + -->
<!--   geom_line() + -->
<!--   geom_point(alpha = 0.5, size = 1) + -->
<!--   scale_linetype_discrete(name = "Dataset") + -->
<!--   labs(x = "Iteration (k)", -->
<!--        y = "Scaled loss", -->
<!--        color = "Metric", -->
<!--        title = "PESCAR: objectives") + -->
<!--   theme_minimal() -->


<!-- (ploss1 + p) / (ploss2 + p_heat) / (ploss3 + p_ray) #+ (p/  p_heat/  p_ray) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- image(B) -->


<!-- vx <- varimax(B)$rotmat  # R x R, orthogonal -->
<!-- A_rot <- A %*% vx -->
<!-- B_rot <- B %*% vx -->

<!--  coefs2 <- solve(t(A_rot[,]) %*% A_rot[,]) %*% t(A_rot[,]) %*% y  -->
<!-- ``` -->


<!-- ```{r} -->
<!-- L1 <- sapply(PESCARmod$lossl, function(x) as.numeric(x$loss)) -->
<!-- L2 <- sapply(PESCARmod$loss, function(x) as.numeric(x$loss)) -->

<!-- L <- c(rbind(L1, L2)) -->

<!-- ## Monotone nonincreasing? -->
<!-- all(diff(L) <= 0) -->

<!-- src <- rep(c("loss","loss2"), length(L1)) -->
<!-- k   <- rep(seq_along(L1), each = 2) -->
<!-- d   <- diff(L) -->
<!-- idx <- which(d > 0) -->

<!-- # Table of violations (if any) -->
<!-- viol <- data.frame( -->
<!--   step      = idx + 1, -->
<!--   from_src  = src[idx],   from_k  = k[idx],   from_loss = L[idx], -->
<!--   to_src    = src[idx+1], to_k    = k[idx+1], to_loss   = L[idx+1], -->
<!--   delta     = d[idx], -->
<!--   row.names = NULL -->
<!-- ) -->
<!-- viol -->
<!-- ``` -->







<!-- PLOTTING ROT -->

<!-- ```{r} -->
<!-- # B <- PESCARmod$outcome$B -->
<!-- # A <- PESCARmod$outcome$A -->
<!-- # -->
<!-- # vx <- varimax(B)$rotmat  # R x R, orthogonal -->
<!-- # A_rot <- A %*% vx -->
<!-- # B_rot <- B %*% vx -->

<!-- A <- A_rot -->
<!-- B <- B_rot -->
<!-- # B <- center_columns_at_mode(B) -->


<!-- Coefs <- (solve(t(A)%*%A) %*% t(A) %*% y_samp) -->

<!-- B_y_ord <- B[,order(abs(Coefs), decreasing = T)] -->
<!-- A_y_ord <- A[,order(abs(Coefs), decreasing = T)] -->

<!-- Coefs_ord <- Coefs[order(abs(Coefs), decreasing = T)] -->


<!-- #loadings and VE plots here from PESCAR implementation on real data -->
<!-- df <- cbind.data.frame(do.call(c,lapply(Data,colnames)) ,do.call(c,lapply(Data,colnames)),rbind(B_y_ord,t(Coefs_ord))) -->

<!-- # do.call(c,lapply(Data,colnames)) -->


<!-- colnames(df)[1:2] <- c("assay","Feature") -->


<!-- df$assay <- rep(names(Data), lapply(Data,ncol)) -->


<!-- colnames(df)[-c(1,2)] <- paste0("PC",colnames(df)[-c(1,2)]) -->


<!-- # colours = c("Gene" = "#A020F0", "Bacteria" = "#FFA500", "Metabolite" = "#55BB99", "Y" = "black") -->
<!-- # colours = c("Gene" = "blue", "Bacteria" = "yellow", "Metabolite" = "red", "Y" = "black") -->
<!-- colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black") -->


<!-- # pdf(paste0(Sys.Date(),"_feature_loadings_project_full2.pdf")) -->
<!-- loadings <- ggplot(df, aes(x = PC1,y = PC2, colour = assay, alpha = 0.5)) + -->
<!--   geom_point(alpha = 0.5) + -->
<!--   scale_color_manual(values = colours) + -->
<!--   ggtitle("Loadings") + -->
<!--   theme_bw() -->


<!-- data <- df -->

<!-- y1 <- Coefs_ord -->

<!--   U <- df[] -->
<!--   rownames(U) <- U$Feature -->
<!--   U <- data.matrix(U[,-c(1,2)]) -->


<!--   UTP <- (dot(t(U),y1)/dot(y1,y1)) -->

<!--   UTP <- cbind.data.frame(names(UTP), UTP, U) -->

<!--   ranked <- as.data.frame(UTP[order(abs(UTP$UTP), decreasing = T),]) -->

<!--   data$UTP   <- UTP[,2] -->



<!-- df_long <- data %>% -->
<!--   pivot_longer( -->
<!--     cols      = 3:(ncol(.) -1),       # columns with numeric data -->
<!--     names_to  = "Component",     # new column for component name -->
<!--     values_to = "Loading"        # new column for numeric values -->
<!--   ) -->


<!-- PESCA_lod_Struc_ggplot <- ggplot(df_long, -->
<!--                                  aes(x = Component, -->
<!--                                      y = Loading, -->
<!--                                      group = Feature,   # each row is a separate line -->
<!--                                      color = assay, alpha = UTP)) + -->
<!--   geom_line(, show.legend = FALSE) + -->
<!--     geom_line(data = df_long[which(df_long$assay == "Y"),], alpha = 1, size = 1.5, show.legend = FALSE) + -->

<!--   scale_color_manual(values = colours) + -->
<!--   # labs(title = "PESCA", x = "Component", y = "Loading") + -->
<!--   theme_ipsum() +  # Optional, from hrbrthemes -->
<!--   theme(plot.title = element_text(size = 10)) + -->
<!--   theme_void() -->

<!-- PESCA_lod_Struc_ggplot -->



<!-- ``` -->


<!-- ```{r} -->
<!-- df <- cbind.data.frame(do.call(c,lapply(Data,colnames)) ,do.call(c,lapply(Data,colnames)),rbind(B,t(Coefs))) -->

<!-- # do.call(c,lapply(Data,colnames)) -->


<!-- colnames(df)[1:2] <- c("assay","Feature") -->


<!-- df$assay <- rep(names(Data), lapply(Data,ncol)) -->


<!-- colnames(df)[-c(1,2)] <- paste0("PC",colnames(df)[-c(1,2)]) -->


<!-- # colours = c("Gene" = "#A020F0", "Bacteria" = "#FFA500", "Metabolite" = "#55BB99", "Y" = "black") -->
<!-- # colours = c("Gene" = "blue", "Bacteria" = "yellow", "Metabolite" = "red", "Y" = "black") -->
<!-- colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black") -->


<!-- df_gg <- data.frame( -->
<!--   # Flatten B by column -->
<!--   x = c((B)), -->
<!--   # Flatten the repeated Coefs by column -->
<!--   y = c(matrix(rep(Coefs, nrow(B)), nrow = nrow(B), byrow = TRUE)), -->
<!--   # Keep track of which column each point came from -->
<!--   col_index = rep(1:ncol(B), each = nrow(B)) -->
<!-- ) -->

<!-- feature_vec <- do.call(c, lapply(Data[1:3], colnames)) -->
<!-- assay_vec   <- rep(names(Data)[1:3], times = lapply(Data[1:3], ncol)) -->

<!-- length(feature_vec) -->
<!-- length(assay_vec) -->

<!-- df_gg$Feature <- rep(feature_vec, ncol(B)) -->
<!-- df_gg$assay   <- rep(assay_vec,    ncol(B)) -->


<!-- head(df_gg) -->


<!-- y1 <- Coefs -->

<!--   U <- df[!df$assay == "Y", ] -->
<!--   rownames(U) <- U$Feature -->
<!--   U <- data.matrix(U[,-c(1,2)]) -->


<!--   UTP <- (dot(t(U),y1)/dot(y1,y1)) -->

<!--   UTP <- cbind.data.frame(names(UTP), UTP, U) -->

<!--   ranked <- as.data.frame(UTP[order(abs(UTP$UTP), decreasing = T),]) -->

<!--   df_gg$UTP   <- rep(UTP[,2],    ncol(B)) -->

<!-- library(ggplot2) -->

<!-- p_coef_ord <- ggplot(df_gg, aes(x = y, y = x, color = assay, alpha = UTP)) + -->
<!--   # geom_point() + -->
<!--   labs( -->
<!--     # color = "Column", -->
<!--     x = "Features", -->
<!--     y = "Component Coefficient" -->
<!--   ) + -->
<!--   geom_line(aes( group = Feature)) + -->
<!--   scale_alpha_continuous() + -->
<!--     # geom_line(data = df_long[which(df_long$assay == "Y"),], alpha = 1, size = 2, show.legend = FALSE) +   # Baits here -->

<!--   scale_color_manual(values = colours) + -->
<!--   # labs(title = "PESCA", x = "Component", y = "Loading") + -->
<!--   # theme_ipsum() +  # Optional, from hrbrthemes -->
<!-- geom_abline(intercept = 0, slope = 1, size = 2) + -->
<!--   theme_minimal() -->

<!-- # p_coef_ord -->

<!-- ``` -->


<!-- ```{r} -->

<!-- var_exp_lr <- function(X_blocks, B) { -->
<!--   L <- length(X_blocks) -->
<!--   d <- vapply(X_blocks, ncol, 0L) -->
<!--   R <- ncol(B) -->
<!--   # block row indices for B -->
<!--   idx <- split(seq_len(sum(d)), rep(seq_len(L), d)) -->
<!--   # denominators: ||X_l - 1*mu_l||_F^2 -->
<!--   denom <- sapply(X_blocks, function(X) { -->
<!--     Xc <- sweep(X, 2, colMeans(X), "-") -->
<!--     sum(Xc^2) -->
<!--   }) -->
<!--   # numerators: ||B_{l,·r}||_2^2 -->
<!--   ve <- matrix(NA_real_, L, R) -->
<!--   for (l in seq_len(L)) { -->
<!--     Bl <- B[idx[[l]], , drop = FALSE] -->
<!--     num <- colSums(Bl^2) -->
<!--     ve[l, ] <- num / denom[l] -->
<!--   } -->
<!--   # optional labels -->
<!--   rownames(ve) <- paste0("block", seq_len(L)) -->
<!--   colnames(ve) <- paste0("PC", seq_len(R)) -->
<!--   # convenient totals (can delete if you want only ve) -->
<!--   attr(ve, "block_total") <- rowSums(ve) -->
<!--   attr(ve, "full_per_component") <- colSums(B^2) / sum(denom) -->
<!--   attr(ve, "full_total") <- sum(colSums(B^2)) / sum(denom) -->
<!--   ve -->
<!-- } -->

<!-- varexpdat <- var_exp_lr(Data[1:3],B) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- data <- log2(varexpdat[,order(abs(Coefs), decreasing = T)] + 1) -->

<!-- colnames(data) <- paste0("PC",1:ncol(data)) -->

<!-- rownames(data) <- c(names(Data)[1:3]) -->



<!-- max_val <- max(colSums(data)) -->

<!-- data <- melt(t(data)) -->
<!-- # colours2 <- c(colours, "Full" = "yellow") -->



<!-- colnames(data)[1:2] <- c("Component","assay") -->

<!-- # data <- data[-which(data$assay == "Full"),] -->

<!-- # Stacked -->
<!-- r_VE <- ggplot(data, aes(fill=assay, y=value, x=Component)) + -->
<!--   scale_fill_manual(values = colours, guide = "none") + -->
<!--     geom_bar(position="stack", stat="identity") + -->
<!--   coord_polar(start = 0) + -->
<!--   theme_bw()+ -->
<!--   theme(axis.line=element_blank(), panel.border=element_blank(), -->
<!--         axis.text.y=element_blank(),axis.ticks=element_blank()) +  #,axis.text.x=element_blank() -->
<!--   # theme_void() + -->
<!--   ylab("")+ -->
<!--   xlab("") + -->
<!--   ylim(-1,max_val) + theme_void() -->

<!-- ``` -->

<!-- ```{r} -->
<!-- # Data_model_df <- A %*% t(B) -->

<!-- Data_model_df <- A %*%  t(B)    # data model y related   ->  diag(c(Coefs)) %*% -->


<!-- colnames(Data_model_df) <- do.call(c, lapply(Data[1:3], colnames)) -->

<!-- y_model <- do.call(cbind,Data[1:3]) %*% PESCARmod$outcome$W_k %*% Coefs -->

<!-- Data_model <- list(Data) -->

<!-- colours = c("X2" = "#0011FF", "X3" = "#FB0000", "X1" = "#11AA00", "Y" = "black") -->



<!-- Data_model <- lapply( -->
<!--   do.call(c,lapply(Data, function(i) unique(gsub("_.*","",colnames(i))))), -->
<!--   function(p) Data_model_df[, grep(p, colnames(Data_model_df)), drop = FALSE] -->
<!-- ) -->

<!-- ch <- ggplot(melt(Data_model[[1]]), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#11AA00", high = "black", low = "white", guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines')) -->


<!-- gh <- ggplot(melt(Data_model[[2]]), aes(x = Var2, y = Var1, fill = value)) + -->
<!--   geom_tile() + -->
<!--   scale_fill_gradient2(mid = "#0011FF", high = "black", low = "white", guide="none") + -->
<!--   theme_void() + -->
<!--   theme( -->
<!--     plot.margin = unit(c(0,0.2,0,1), "lines")) -->


<!-- bh <- ggplot(melt(Data_model[[3]]), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#FB0000", high = "black", low = "white",guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines')) -->


<!-- yh <- ggplot(melt(y_model), aes(x = Var2, y = Var1, fill = value)) + geom_tile() + scale_fill_gradient2(mid = "#002060", high = "black", low = "white",guide="none") + theme_void() + theme(plot.margin = unit(c(0,0.2,0,1), 'lines')) -->


<!-- # (bh + plot_spacer()) + (gh + plot_spacer()) + ch + yh -->

<!-- p11 <- ggarrange(ch, gh, bh, yh, nrow = 1, widths = c(4,4,4,1)) -->

<!-- ``` -->




<!-- ```{r} -->
<!-- library(igraph) -->
<!-- library(dplyr) -->
<!-- library(tidyr) -->
<!-- library(tidygraph) -->
<!-- library(lubridate) -->
<!-- # library(iterpc) -->
<!-- library(ggraph) -->
<!-- library(tidygraph) -->

<!-- set.seed(123) -->
<!-- B_y_ord <- B[,order(abs(Coefs), decreasing = T)] -->

<!-- colnames(B_y_ord) <- paste0("PC",1:ncol(B_y_ord)) -->

<!-- # cor_matrix <- as.matrix(cor(rbind(B,t(Coefs)))) -->
<!-- cor_matrix <- as.matrix(cor(B_y_ord)) -->

<!-- Coefs_ord <- Coefs[order(abs(Coefs), decreasing = T)] -->

<!-- cor_matrix <- cbind(Coefs_ord, cor_matrix) -->
<!-- cor_matrix <- rbind(c(1,Coefs_ord), cor_matrix) -->

<!-- cor_matrix[lower.tri(cor_matrix)] <- t(cor_matrix)[lower.tri(cor_matrix)] -->
<!-- # Set diagonal to 1 (typical for correlation) -->
<!-- diag(cor_matrix) <- 1 -->

<!-- cor_matrix[which(is.na(cor_matrix))] <- 0 -->

<!-- colnames(cor_matrix) <- c("Y",paste0("PC",c(1:opts$R))) -->


<!-- g <- graph_from_adjacency_matrix( -->
<!--   cor_matrix, -->
<!--   mode = "undirected", -->
<!--   weighted = TRUE, -->
<!--   diag = FALSE -->
<!-- ) -->




<!-- x <- varexpdat[,order(abs(Coefs), decreasing = T)] -->
<!-- # x <- sweep(x, 1, pmax(1, ncol(x) - rowSums(x != 0)), FUN = "/") -->

<!-- SCALLY_WAH <- function(i){i/max(abs(i))} -->


<!-- x1 <- sweep(x, 1, pmax(1, ncol(x) - rowSums(x != 0)), FUN = "/") -->
<!-- x1 <- x1[1:3,] -->
<!-- x1 <- apply(x1[,],2,SCALLY_WAH) -->
<!-- x1[which(is.na(x1))] <- 0 -->
<!-- x1[x1<0] <- 0 -->



<!-- r <- x1[3,] -->
<!-- gr <- x1[1,] -->
<!-- b <- x1[2,] -->

<!-- col <- rgb(r, gr, b) -->
<!-- dim(col) <- dim(r) -->

<!-- col <- c("#002060", col) -->


<!-- V(g)$colour <- col  #c(rep(c("#A020F0","#00B050","#FFA500"), each = 10), "#002060")   # use CLD for this too -->



<!-- threshold <- 0.1     # - WARNING - -->
<!-- # Remove edges whose absolute weight is below that threshold -->
<!-- g <- delete_edges(g, E(g)[abs(weight) < threshold]) -->

<!-- g <- delete_vertices(simplify(g), degree(g)==0) -->

<!-- edge_weights <- E(g)$weight -->
<!-- edge_colors  <- ifelse(edge_weights > 0, "red", "blue") -->

<!-- E(g)$weight <- abs(E(g)$weight) -->

<!-- E(g)$colour <- edge_colors -->
<!-- #make vertex_size vector -->

<!-- set.seed(100) -->
<!-- # 7. Plot the graph -->
<!-- plot( -->
<!--   g, -->
<!--   layout = layout_with_fr(g), -->
<!--   # vertex.label       = V(g)$name, -->
<!--   vertex.color       = V(g)$colour, -->
<!--   vertex.size        = 15, -->
<!--   vertex.label = NA, -->
<!--   edge.width         = abs(edge_weights) ,  # scale by absolute correlation -->
<!--   edge.color         = edge_colors -->
<!-- ) -->

<!-- # "#3D833F" "#39883E" "#417A44" "#83007C" "#7E0081" "#890076" "#002060" -->

<!-- V(g)$shape <- gsub("\\d$","",names(V(g))) -->


<!-- tg <- as_tbl_graph(g) -->



<!-- #create layout matrix - HERE - -->
<!-- set.seed(100) -->
<!-- p <- ggraph(tg, layout = "fr") + -->

<!--   geom_edge_link(aes(edge_width = weight, color = I(colour))) + -->

<!--   geom_node_point(aes(color = I(colour), shape = shape), size = 0) + -->

<!--   theme_void() + -->
<!--   # Possibly override scale for edge_width -->
<!--   scale_edge_width(range = c(0.5, 1), guide = "none") + -->
<!--   scale_shape_discrete(guide = "none") -->

<!-- # p -->

<!-- # "#002060" "#409DFF" "#C5FFA9" "#07FFB9" "#07F2FF" "#FF617B" -->

<!-- ``` -->

<!-- ```{r} -->

<!-- library(ggraph) -->
<!-- library(tidygraph) -->
<!-- library(igraph) -->
<!-- library(ggplot2) -->

<!-- set.seed(100) # - WARNING - -->


<!-- layout_data <- create_layout(tg, layout = "fr") -->


<!-- col <- V(g)$colour -->


<!-- offset <- 0.4 -->

<!-- i <- NULL -->
<!-- for (i in seq_len(nrow(layout_data))) { -->
<!--   x_i <- layout_data$x[i] -->
<!--   y_i <- layout_data$y[i] -->

<!--   if(i == 1){ -->

<!--     mat <- as.matrix(y_model) -->

<!--   }else{ -->

<!--     # mat <- A[,(i - 1)] %*% t(B[,(i - 1)]) -->

<!--         mat <- as.matrix(A_y_ord[,(i - 1)]) -->


<!--   } -->
<!--   # Scale to [0,1] -->
<!--   mat_scaled <- (mat - min(mat)) / (max(mat) - min(mat)) -->

<!--   # Build a color palette and index into it -->
<!--   pal <- colorRampPalette(c("white",col[i],"black"))(256) -->
<!--   # Convert numeric values into actual color strings -->
<!--   mat_colors <- pal[as.integer(mat_scaled * 255) + 1] -->

<!--   # Reshape 'mat_colors' into the same dimension as 'mat' -->
<!--   mat_colors <- matrix(mat_colors, nrow = nrow(mat), ncol = ncol(mat)) -->

<!--   # Now we can add an annotation_raster layer for that matrix of color strings -->
<!--   p <- p + annotation_raster( -->
<!--     raster = mat_colors, -->
<!--     xmin   = x_i - offset, xmax = x_i + offset, -->
<!--     ymin   = y_i - offset, ymax = y_i + offset, -->
<!--     interpolate = FALSE  # TRUE could look good -->
<!--   ) -->

<!-- } -->

<!-- p <- p + -->
<!--     geom_node_text(aes(label = name), -->
<!--                  repel = TRUE,    # keep labels from overlapping -->
<!--                  color = "black") -->



<!-- x_range <- range(layout_data$x) -->
<!--  y_range <- range(layout_data$y) -->

<!--  # offset <- 0.3 -->

<!--  p <- p + coord_cartesian( -->
<!--      xlim = c(x_range[1] - offset, x_range[2] + offset), -->
<!--      ylim = c(y_range[1] - offset, y_range[2] + offset), -->
<!--      clip = "off" -->
<!--  ) -->

<!--  # 7) Optionally add some plot margin so nothing is clipped by the plot boundary -->
<!--  p <- p + theme( -->
<!--      plot.margin = unit(c(1,1,1,1), "cm") -->
<!--  ) # -->
<!--  print(p) -->

<!-- ``` -->


<!-- - HERE - -->



<!-- ```{r} -->


<!-- ((PESCA_lod_Struc_ggplot + r_VE)/       #p_coef_ord -->
<!--   p11) + (p)  # + cube_plot) -->

<!-- plottings <- FALSE -->
<!-- if(plottings == TRUE){ -->
<!--   ggsave(paste0(Sys.Date(),"_PESCAR_",alpha,"_",opts$R,"_comp.tiff")) -->

<!-- } -->
<!-- ``` -->



